name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm 10.15.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          standalone: true

      - name: Versions
        run: |
          node -v
          pnpm -v

      - name: Install deps (workspace)
        run: pnpm install

      - name: Build (Turbo if present; else Next in apps/web)
        run: |
          if [ -f turbo.json ]; then
            pnpm -w dlx turbo run build --filter=apps/web --no-cache
          else
            cd apps/web && pnpm run build
          fi
