name: CI
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with: { bun-version: 1.2.21 }
      - run: bun install
      - run: bunx turbo run lint --continue
      - run: bunx turbo run build --continue
