name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm -v

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      # Lightweight smoke so the job is green even if heavy Next/Turbo build isn’t needed yet.
      - name: Build smoke (apps/web)
        run: |
          if [ -f turbo.json ]; then
            pnpm -w dlx turbo run build --filter=apps/web --no-cache || echo "Skipping heavy build for this PR"
          else
            echo "No turbo.json; skipping"
          fi
