name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack / activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm -v

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm -w dlx turbo run build --filter=apps/web --no-cache
