name: Guardrails FDA Eval
on:
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder eval
        run: echo "✅ Guardrails FDA placeholder passing check"
