name: Guardrails FDA Eval
on:
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout

      my(,,)=(        uses: actions/checkout@v4
,        ,);
      (=~/fetch-depth:s*0/)? . : .inject(."  ").
    