name: Sanity (prod)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sanity:
    runs-on: ubuntu-latest
    env:
      PROD_URL: ${{ secrets.PROD_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install curl & jq
        run: sudo apt-get update && sudo apt-get install -y curl jq
      - name: Sanity
        run: bash scripts/prod-sanity.sh
