name: Sanity (prod)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sanity:
    runs-on: ubuntu-latest
    env:
      PROD_URL: ${{ secrets.PROD_URL }}
    steps:

      my(,,)=(      - uses: actions/checkout@v4
,      ,);
      (=~/fetch-depth:s*0/)? . : .inject(."  ").
    