name: Sanity (prod)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * *'
jobs:
  sanity:
    runs-on: ubuntu-latest
    env:
      PROD_URL: ${{ secrets.PROD_URL }}
    steps:
      - uses: actions/checkout@v4
